### ISSUE TITLE
PlotConfig variable name casing to plotly attribute casing

### ISSUE THREAD

**Issue by elipivo** [GenieFramework/StipplePlotly.jl#54] opened 2022-12-16 17:07 UTC
It appears that some of the PlotConfig options aren't getting translated to the html component correctly. For instance,

`plot("data", layout=PlotLayout(), config=:config)`

is translated to

`<plotly :data=\"data\" :layout=\"{}\" :responsive=\"typeof config.responsive == 'undefined' ? true : config.responsive\" :editable=\"typeof config.editable == 'undefined' ? false : config.editable\" :scroll-zoom=\"typeof config.scrollzoom == 'undefined' ? false : config.scrollzoom\" :static-plot=\"typeof config.staticplot == 'undefined' ? false : config.staticplot\" :display-mode-bar=\"typeof config.displaymodebar == 'undefined' ? true : config.displaymodebar\" :displaylogo=\"typeof config.displaylogo == 'undefined' ? '' : config.displaylogo\" :to-image-button-options=\"typeof config.toImageButtonOptions == 'undefined' ? {'filename':'newplot','height':500,'format':'png','scale':1,'width':700} : config.toImageButtonOptions\"></plotly>`

On the browser side, the config object has properties `displayModeBar`, `scrollZoom`, and `staticPlot`. Therefore these options always show up as `undefined` and aren't getting set correctly.

**Comment by hhaensel** [comment] 2023-03-23 00:03
From your example it is not clear, how you set the config field. Could you please post a MWE with a model containing a field `config` and set this to a valid configuration?

**Comment by LMW38** [comment] 2024-01-13 11:23
It is been a while since last comment in this feed. Even so, in my opinion,  it is still relevant to get the configs option right.

@hhaensel: here is a MWE:

```Julia
using Stipple, Stipple.ReactiveTools
using StippleUI
using StipplePlotly
 
pd(name) = PlotData(
  x = ["Jan2019", "Feb2019", "Mar2019", "Apr2019", "May2019",
        "Jun2019", "Jul2019", "Aug2019", "Sep2019", "Oct2019",
        "Nov2019", "Dec2019"],
  y = Int[rand(1:100_000) for x in 1:12],
  plot = StipplePlotly.Charts.PLOT_TYPE_SCATTER,
  name = name
)
 
@app PlotModel begin
    @out data = [pd("Random 1"), pd("Random 2")]
    @out layout = PlotLayout(plot_bgcolor = "#fff", title = PlotLayoutTitle(text="Random numbers", font=Font(14)))
    @out config = PlotConfig(toimage_format="svg", toimage_filename="imagename", displaylogo=false)
end
 
function ui()
    [
        plot(:data; layout = :layout, config = :config)
    ] |> join
end
 
route("/") do
    model = @init(PlotModel)
    page(model, ui()) |> html
end
 
up()
```

This example is adopted from example "example1_newapi.jl" (I think it is created by @AbhimanyuAryan) in StippleDemos/StipplePlotly repository. At this time of writing, on Windows and MacOS using the latest releases of GenieFramework, the result is the same as reported by @elipivo in the first post. Julia version did not matter.

At the moment, I am studying the code but, in the meantime, you may have hints to get me a head start. It seems layout and config are treated differently, so I am trying to nail this issue.

I would like to mention Stipple is an awesome package! My users like the look, feel & responsiveness of the graphs created with StipplePlotly. The common feedback is that users would love to have more meaningful names for downloaded images from the app, as well as select image type (png, svg, etc.).

**Comment by hhaensel** [comment] 2024-03-05 12:15
The issue is probably from a new vueplotly version that handles config differently than previous versions.
I've released a new version that fixes the issue.
Please test and close the issue if it is solved.

**Closed** 2024-03-06 17:49 UTC
